## Path configuration: absolute paths to data (.ab1 files) and output directory on host machine and in mounted Docker container
paths:
  #folder paths on host machine
  data_host: 'data/sanger_seq'
  outdir_host: 'outdir/sanger_seq'
  samplesheet: 'data/sanger_seq/samplesheet.csv'

## Tracy software configuration
tracy:
  # trimming length: number nucleotides at 5' (left) and 3' (right) to be removed
  trim_left: 50
  trim_right: 200
