## Path configuration: absolute paths to data (.ab1 files) and output directory on host machine and in mounted Docker container
paths:
  #paths on host machine
  data_host: '/Users/sebschu/Documents/senDS_cfb/code/dsp_bulk-sangerseq/data/sanger_seq'
  outdir_host: '/Users/sebschu/Documents/senDS_cfb/code/dsp_bulk-sangerseq/outdir/sanger_seq'

  #paths in docker container
  data_docker: '/home/sanger_seq/data'
  outdir_docker: '/home/sanger_seq/outdir'


## Docker configuration
docker:
  image: 'geargenomics/tracy'
  version: 'latest'


## Tracy software configuration
tracy:
  # name of reference fasta file to align to
  ref_name: 'reference.fa'

  # outfile name --> only needed for testing
  outfile_name: 'bulk_test'

  # trimming length: number nucleotides at 5' (left) and 3' (right) to be removed
  trim_left: 50
  trim_right: 200


