## Path configuration: absolute paths to data (.ab1 files) and output directory on host machine and in mounted Docker container
paths:
  #folder paths on host machine
  data_host: './data/test_data_1'
  outdir_host: './outdir/test_data_1'
  samplesheet: './data/test_data_1/samplesheet_test_data_1_multi_ref_grouping_2samples.csv'
  reference_fasta: './data/test_data_1/references.fa'

  #paths in docker container
  data_docker: '/home/sanger_seq/data'
  outdir_docker: '/home/sanger_seq/outdir'

## Tracy software configuration
tracy:
  # trimming length: number nucleotides at 5' (left) and 3' (right) to be removed
  trim_left: 50
  trim_right: 50

  # trimming stringency for automatic determination of trimming length
  # [1:9} with 1 being the lowest and 9 the highest stringency, 0: disable
  # tracy default trimming stringency values for each command are defined here
  trim_stringency_decompose: 0
  trim_stringency_align: 0
  trim_stringency_assemble: 4



## Docker configuration
docker:
  image: 'geargenomics/tracy'
  version: 'latest'
  platform: 'linux/amd64'

## HTML visualisation configuration
visualisation:
  image: 'ghcr.io/biosustain/tracy-visualisations'
  tag: 'latest'
  platform: 'linux/amd64'



