x-tracy-service: &tracy-service
    image: 'geargenomics/tracy:latest'
    platform: linux/amd64
    environment:
        REFERENCE_NAME: ${REFERENCE_NAME?Missing reference .ab1 file to use}
        SAMPLE_ID: ${SAMPLE_ID?Missing sample ID}
        FILE_NAME: ${FILE_NAME?Missing .ab1 file to use}
        TRIM_LEFT: ${TRIM_LEFT?Missing trim left value}
        TRIM_RIGHT: ${TRIM_RIGHT?Missing trim right value}
        DATA_HOST: ${DATA_HOST?Missing data host path}
        OUTDIR_HOST: ${OUTDIR_HOST?Missing output directory path}
    volumes:
        - "${DATA_HOST?}:/home/sanger_seq/data:ro"
        - "${OUTDIR_HOST?}:/home/sanger_seq/outdir"
    stdin_open: true
    tty: true

services:
    tracy_decompose:
        <<: *tracy-service
        container_name: "decompose_${SAMPLE_ID}"
        command: bash -c "
            tracy decompose -v \
                -r /home/sanger_seq/data/${REFERENCE_NAME} \
                -o /home/sanger_seq/outdir/${SAMPLE_ID} \
                --trimLeft ${TRIM_LEFT} \
                --trimRight ${TRIM_RIGHT} \
                /home/sanger_seq/data/${FILE_NAME}"

    tracy_align:
        <<: *tracy-service
        container_name: "align_${SAMPLE_ID}"
        command: bash -c "
            tracy align -r /home/sanger_seq/data/${REFERENCE_NAME} \
                -o /home/sanger_seq/outdir/${SAMPLE_ID} \
                --trimLeft ${TRIM_LEFT} \
                --trimRight ${TRIM_RIGHT} \
                /home/sanger_seq/data/${FILE_NAME}"
